INSERT INTO public.products (name, slug, description, price, image_url, franchise, character, category, stock, is_featured) VALUES
('Pop! Spider-Man #39', 'spider-man-39', 'El iconico Spider-Man en su traje clasico rojo y azul.', 14.99, 'https://i.imgur.com/placeholder.png', 'Marvel', 'Spider-Man', 'Standard', 25, true),
('Pop! Iron Man Mark 50 #285', 'iron-man-285', 'Tony Stark con la armadura Mark 50 de Infinity War.', 16.99, 'https://i.imgur.com/placeholder.png', 'Marvel', 'Iron Man', 'Deluxe', 18, true),
('Pop! Thanos #289', 'thanos-289', 'Thanos con el guantelete del infinito.', 19.99, 'https://i.imgur.com/placeholder.png', 'Marvel', 'Thanos', 'Deluxe', 12, true),
('Pop! Wolverine #555', 'wolverine-555', 'Logan con sus garras de adamantio extendidas.', 14.99, 'https://i.imgur.com/placeholder.png', 'Marvel', 'Wolverine', 'Standard', 20, false),
('Pop! Captain America #10', 'captain-america-10', 'Steve Rogers con su escudo indestructible.', 14.99, 'https://i.imgur.com/placeholder.png', 'Marvel', 'Captain America', 'Standard', 30, false),
('Pop! Black Widow #603', 'black-widow-603', 'Natasha Romanoff con traje negro y pistolas.', 13.99, 'https://i.imgur.com/placeholder.png', 'Marvel', 'Black Widow', 'Standard', 22, false),
('Pop! Thor #700', 'thor-700', 'El dios del trueno con su hacha Stormbreaker.', 15.99, 'https://i.imgur.com/placeholder.png', 'Marvel', 'Thor', 'Standard', 15, false),
('Pop! Doctor Strange #414', 'doctor-strange-414', 'Stephen Strange con la Capa de Levitacion.', 14.99, 'https://i.imgur.com/placeholder.png', 'Marvel', 'Doctor Strange', 'Standard', 17, false),
('Pop! Venom #363', 'venom-363', 'Eddie Brock fusionado con el simbionte.', 16.99, 'https://i.imgur.com/placeholder.png', 'Marvel', 'Venom', 'Deluxe', 8, true),
('Pop! Groot Chase #264', 'groot-264-chase', 'Baby Groot con flor. Edicion Chase rara.', 24.99, 'https://i.imgur.com/placeholder.png', 'Marvel', 'Groot', 'Chase', 5, true),
('Pop! Batman #01', 'batman-01', 'El Caballero Oscuro en su traje clasico.', 14.99, 'https://i.imgur.com/placeholder.png', 'DC', 'Batman', 'Standard', 28, true),
('Pop! Joker #53', 'joker-53', 'El Payaso Principe del Crimen en smoking morado.', 14.99, 'https://i.imgur.com/placeholder.png', 'DC', 'Joker', 'Standard', 20, false),
('Pop! Wonder Woman #172', 'wonder-woman-172', 'Diana con escudo y lasso dorado de la verdad.', 14.99, 'https://i.imgur.com/placeholder.png', 'DC', 'Wonder Woman', 'Standard', 18, false),
('Pop! Superman #01', 'superman-01', 'El Hombre de Acero en pose de vuelo.', 14.99, 'https://i.imgur.com/placeholder.png', 'DC', 'Superman', 'Standard', 22, false),
('Pop! The Flash #713', 'the-flash-713', 'Barry Allen en traje escarlata.', 15.99, 'https://i.imgur.com/placeholder.png', 'DC', 'The Flash', 'Standard', 14, false),
('Pop! Harley Quinn #368', 'harley-quinn-368', 'Harley con mazo gigante y outfit bicolor.', 14.99, 'https://i.imgur.com/placeholder.png', 'DC', 'Harley Quinn', 'Standard', 25, true),
('Pop! Mickey Mouse #01', 'mickey-mouse-01', 'El raton mas famoso del mundo version clasica.', 12.99, 'https://i.imgur.com/placeholder.png', 'Disney', 'Mickey Mouse', 'Standard', 35, true),
('Pop! Elsa #593', 'elsa-593', 'La reina de las nieves de Arendelle.', 13.99, 'https://i.imgur.com/placeholder.png', 'Disney', 'Elsa', 'Standard', 20, false),
('Pop! Simba #301', 'simba-301', 'El cachorro Simba del Rey Leon.', 12.99, 'https://i.imgur.com/placeholder.png', 'Disney', 'Simba', 'Standard', 18, false),
('Pop! Stitch #159', 'stitch-159', 'El experimento 626 color azul adorable.', 13.99, 'https://i.imgur.com/placeholder.png', 'Disney', 'Stitch', 'Standard', 22, true),
('Pop! Woody #168', 'woody-168', 'El vaquero favorito de Andy.', 12.99, 'https://i.imgur.com/placeholder.png', 'Disney', 'Woody', 'Standard', 15, false),
('Pop! Darth Vader #01', 'darth-vader-01', 'El Senor Sith con sable de luz rojo.', 14.99, 'https://i.imgur.com/placeholder.png', 'Star Wars', 'Darth Vader', 'Standard', 30, true),
('Pop! Grogu #369', 'grogu-369', 'Baby Yoda usando la Fuerza.', 15.99, 'https://i.imgur.com/placeholder.png', 'Star Wars', 'Grogu', 'Standard', 40, true),
('Pop! Yoda #02', 'yoda-02', 'El maestro Jedi mas sabio de la galaxia.', 14.99, 'https://i.imgur.com/placeholder.png', 'Star Wars', 'Yoda', 'Standard', 18, false),
('Pop! The Mandalorian #326', 'mandalorian-326', 'Din Djarin con armadura de beskar.', 15.99, 'https://i.imgur.com/placeholder.png', 'Star Wars', 'The Mandalorian', 'Standard', 12, false),
('Pop! Naruto #727', 'naruto-727', 'El Hokage de Konoha en modo Sennin.', 14.99, 'https://i.imgur.com/placeholder.png', 'Anime', 'Naruto', 'Standard', 20, true),
('Pop! Goku Super Saiyan #858', 'goku-858', 'Son Goku en modo Super Saiyan.', 16.99, 'https://i.imgur.com/placeholder.png', 'Anime', 'Goku', 'Standard', 22, true),
('Pop! Pikachu #353', 'pikachu-353', 'El Pokemon numero 1 en pose de ataque.', 12.99, 'https://i.imgur.com/placeholder.png', 'Anime', 'Pikachu', 'Standard', 45, true),
('Pop! Tanjiro #1169', 'tanjiro-1169', 'El cazador de demonios con su katana.', 14.99, 'https://i.imgur.com/placeholder.png', 'Anime', 'Tanjiro', 'Standard', 15, false),
('Pop! Luffy Gear 4 #924', 'luffy-924', 'Monkey D. Luffy en Gear Fourth.', 18.99, 'https://i.imgur.com/placeholder.png', 'Anime', 'Luffy', 'Deluxe', 10, true),
('Pop! Harry Potter #01', 'harry-potter-01', 'El nino que vivio con su varita.', 12.99, 'https://i.imgur.com/placeholder.png', 'Harry Potter', 'Harry Potter', 'Standard', 20, false),
('Pop! Hermione #03', 'hermione-03', 'La mejor bruja de su generacion.', 12.99, 'https://i.imgur.com/placeholder.png', 'Harry Potter', 'Hermione', 'Standard', 18, false),
('Pop! Kratos #269', 'kratos-269', 'El Fantasma de Esparta con las Hojas del Caos.', 16.99, 'https://i.imgur.com/placeholder.png', 'Juegos', 'Kratos', 'Standard', 10, true),
('Pop! Link #21', 'link-21', 'El heroe de Hyrule con espada Maestra.', 14.99, 'https://i.imgur.com/placeholder.png', 'Juegos', 'Link', 'Standard', 15, false),
('Pop! Master Chief #06', 'master-chief-06', 'El espartano con armadura Mjolnir.', 15.99, 'https://i.imgur.com/placeholder.png', 'Juegos', 'Master Chief', 'Standard', 12, false);